 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/store_locators", type: :request do
  
  # StoreLocator. As you add validations to StoreLocator, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      StoreLocator.create! valid_attributes
      get store_locators_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      store_locator = StoreLocator.create! valid_attributes
      get store_locator_url(store_locator)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_store_locator_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      store_locator = StoreLocator.create! valid_attributes
      get edit_store_locator_url(store_locator)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new StoreLocator" do
        expect {
          post store_locators_url, params: { store_locator: valid_attributes }
        }.to change(StoreLocator, :count).by(1)
      end

      it "redirects to the created store_locator" do
        post store_locators_url, params: { store_locator: valid_attributes }
        expect(response).to redirect_to(store_locator_url(StoreLocator.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new StoreLocator" do
        expect {
          post store_locators_url, params: { store_locator: invalid_attributes }
        }.to change(StoreLocator, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post store_locators_url, params: { store_locator: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested store_locator" do
        store_locator = StoreLocator.create! valid_attributes
        patch store_locator_url(store_locator), params: { store_locator: new_attributes }
        store_locator.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the store_locator" do
        store_locator = StoreLocator.create! valid_attributes
        patch store_locator_url(store_locator), params: { store_locator: new_attributes }
        store_locator.reload
        expect(response).to redirect_to(store_locator_url(store_locator))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        store_locator = StoreLocator.create! valid_attributes
        patch store_locator_url(store_locator), params: { store_locator: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested store_locator" do
      store_locator = StoreLocator.create! valid_attributes
      expect {
        delete store_locator_url(store_locator)
      }.to change(StoreLocator, :count).by(-1)
    end

    it "redirects to the store_locators list" do
      store_locator = StoreLocator.create! valid_attributes
      delete store_locator_url(store_locator)
      expect(response).to redirect_to(store_locators_url)
    end
  end
end
